var url = require('./imbiß.jpg')

export default {
  author: 'tueoh',
  artist: 'Imbiß',
  cuarter: 'Berlin',
  gardient: 'linear-gradient(90deg, rgba(60,57,43,1) 0%, rgba(60,57,43,0) 100%),linear-gradient(180deg, rgba(154,140,118,1) 0%, rgba(154,140,118,0) 100%),linear-gradient(270deg, rgba(230,221,216,1) 0%, rgba(230,221,216,0) 100%),linear-gradient(0deg, rgba(89,96,73,1) 0%, rgba(89,96,73,0) 100%)',
  cover: url,
  content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In pharetra, nunc in scelerisque dignissim, metus enim auctor ligula, ac pharetra est magna facilisis ex. In hac habitasse platea dictumst. Vestibulum commodo lorem justo, non finibus ipsum lacinia id. Fusce fermentum arcu at quam maximus, ac commodo quam maximus. Nunc pretium facilisis nibh vel mollis. Praesent commodo placerat nulla aliquam facilisis. Fusce ut semper nisi.

Integer pellentesque elit ut placerat consequat. Ut efficitur faucibus eros vitae aliquet. Nulla bibendum urna turpis, eget bibendum turpis placerat pretium. Morbi imperdiet ipsum at nulla sollicitudin, egestas vehicula tellus cursus. Quisque dignissim quam ut lorem pharetra pulvinar. Fusce sollicitudin dapibus ante, non vehicula mi pulvinar sed. Sed fermentum erat non interdum mattis. Proin turpis turpis, placerat vitae cursus a, porttitor vitae est.

Nunc viverra maximus leo ac tempor. Etiam nec iaculis justo. Maecenas malesuada ultrices ex, sit amet dignissim turpis pretium at. Nullam mattis sodales elit, id blandit quam convallis sit amet. In hac habitasse platea dictumst. Aliquam placerat ut felis sed bibendum. Praesent id orci cursus, porttitor orci sit amet, mattis enim.

Integer blandit, sem id tempor cursus, neque metus placerat lorem, sed egestas metus nisl eu mauris. Pellentesque vitae sapien mauris. Donec tempus eu urna nec aliquam. Ut mollis ut diam ac pellentesque. Etiam ipsum enim, vehicula a enim ac, lacinia finibus dolor. Aenean ut feugiat est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean risus orci, eleifend nec porttitor non, imperdiet id felis. Aliquam sodales pulvinar fringilla.

Nam eu porttitor felis, sed iaculis nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed id lectus finibus, iaculis augue eu, rutrum purus. Nam eu maximus justo. Donec et quam nulla. Praesent eu dignissim erat. Curabitur rutrum fringilla metus vel eleifend. Morbi volutpat mattis nibh, sodales malesuada sem euismod non.

Vestibulum tempor ultricies lacinia. Nam et sapien libero. Morbi eu nisl leo. Vestibulum ut lectus libero. Vestibulum leo odio, porttitor at mi laoreet, porta fringilla lectus. Quisque enim dui, porta ut dolor et, eleifend blandit nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi cursus ipsum est, sed faucibus tortor pellentesque a. Integer dictum convallis mauris, eget elementum velit vulputate id. Nunc sagittis turpis diam, vitae dignissim ex vulputate a. Fusce ultrices risus fringilla nunc rutrum ultricies. In eu arcu a magna varius finibus. Nulla eu elit non nulla ultricies rhoncus. Phasellus molestie pulvinar enim nec efficitur.

Pellentesque sed elit in odio ultricies condimentum at ac ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc felis odio, interdum nec risus eget, fringilla aliquet quam. Fusce porttitor urna enim, et efficitur eros fringilla rhoncus. Phasellus ac erat nulla. Vivamus mattis feugiat dignissim. Mauris pretium est ex, eu imperdiet sapien sagittis lobortis. Suspendisse aliquam auctor aliquam. Aenean sed nisi enim. In ligula massa, vehicula at eleifend et, tincidunt nec sapien. In euismod facilisis quam quis molestie. Nulla a magna leo. Vestibulum ac viverra est, in ornare libero. Nullam vitae finibus ante.

Maecenas vel ex lectus. Vestibulum tempus dui sed turpis pharetra pellentesque. Nulla elementum id mi a consequat. Etiam eget eros velit. Aliquam euismod nunc neque, eget consectetur quam porttitor in. Nulla feugiat sagittis justo, eu pulvinar mi finibus at. Nulla volutpat imperdiet elit vel pharetra. Aenean tincidunt, eros id suscipit eleifend, massa neque maximus lacus, ac iaculis neque ante in nibh. Duis ornare justo venenatis, sagittis nunc id, cursus justo.

Nam felis nulla, imperdiet in aliquet in, condimentum vitae nisi. Curabitur porttitor dignissim enim sit amet placerat. Nulla non pretium diam, ac ullamcorper sem. Donec nec mi convallis, pretium justo id, suscipit metus. Nullam erat enim, luctus ut eros in, laoreet imperdiet magna. Praesent turpis mi, tincidunt et elementum rhoncus, egestas vitae neque. Ut quis tellus eget massa gravida euismod. Proin urna est, imperdiet a orci sed, sollicitudin tincidunt enim. Ut et vulputate est. Donec et elit et urna efficitur cursus et ut mi. In vel pretium orci, at posuere lacus.

Maecenas sed dolor id nibh tristique ultricies. Phasellus dui risus, pharetra quis ligula sit amet, semper auctor nulla. Curabitur molestie gravida lacus eu blandit. Ut quis molestie lorem, pellentesque pellentesque erat. Pellentesque nec mauris tristique, ornare lectus efficitur, feugiat metus. Fusce auctor rhoncus velit, nec mollis ante venenatis mattis. Sed lobortis imperdiet lacus, nec congue dui mattis in. Praesent sagittis feugiat tortor, sit amet posuere diam ultrices eget. Quisque commodo diam quis erat commodo, a facilisis metus bibendum.

In hac habitasse platea dictumst. Suspendisse potenti. Aenean semper placerat est. Fusce suscipit eleifend velit at scelerisque. Donec in arcu justo. Proin nulla turpis, luctus id sollicitudin non, aliquet id nibh. Quisque et volutpat velit, ac dapibus sapien. Mauris ipsum urna, vulputate sed facilisis eget, fermentum a enim.

Nulla eu elit vel diam vulputate accumsan. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras gravida lacus nec bibendum ornare. Pellentesque venenatis lectus nisl, sed lobortis velit ultrices a. Nam ipsum dui, malesuada et laoreet quis, cursus nec ex. Pellentesque et felis tellus. Morbi egestas, risus non vulputate mattis, magna augue maximus tortor, et ultrices lorem leo vel neque. Morbi varius elit id orci consectetur tempor. Vestibulum vitae nisl nulla. Aenean nec neque id ex ultrices tempus vitae sed elit. Duis interdum augue a odio interdum imperdiet. Nunc a luctus leo.

Proin non turpis id diam gravida feugiat eu lacinia justo. Duis fringilla sapien nisl, ac tempor erat hendrerit vitae. Ut purus felis, cursus id malesuada maximus, sodales eget lorem. Etiam suscipit ac justo vel venenatis. In porta nunc in purus iaculis, et dictum mauris egestas. Morbi a varius mauris. Aenean bibendum scelerisque ex vitae faucibus. Integer ultricies eu velit vel euismod. Fusce in erat dignissim, mollis felis et, iaculis dui. Aenean in ligula dui. Nullam neque lectus, volutpat eget ipsum id, egestas placerat mi.

Aenean commodo iaculis luctus. Praesent non tellus fermentum felis rutrum facilisis. Cras quis lorem metus. Nunc malesuada velit nisi, non sagittis libero vulputate ut. Aliquam quis eros dui. Quisque auctor viverra sagittis. Maecenas rhoncus, est eu vehicula semper, orci metus mattis tortor, id posuere nunc mi consequat lacus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse a interdum enim. Vestibulum vestibulum ultricies nibh, in mattis dolor bibendum vel. Vestibulum imperdiet, diam ut rutrum venenatis, tortor odio ultricies odio, quis consectetur lorem velit eget felis. Phasellus vel mauris in dui egestas tincidunt a quis eros. Suspendisse in rutrum sem. Praesent arcu sapien, pharetra ac neque id, rutrum condimentum nisi. Ut mollis pharetra mi vel iaculis. Praesent commodo commodo tincidunt.

Aenean facilisis, quam vitae commodo dictum, leo arcu tristique sapien, et sagittis orci justo a ante. Ut vel urna posuere, auctor nibh id, ullamcorper sem. Duis scelerisque vehicula arcu, a convallis purus sodales eu. Sed venenatis ex facilisis, pharetra ipsum ac, maximus quam. Etiam ultrices semper nibh nec posuere. Nunc ut urna tristique, suscipit mauris at, consectetur massa. Fusce elementum fringilla pulvinar.

Ut sollicitudin euismod rhoncus. Mauris dolor nibh, rutrum in ipsum vitae, commodo bibendum ipsum. Suspendisse vitae imperdiet quam. Curabitur non augue ac dolor cursus rutrum eu sed nisi. Aliquam erat volutpat. Suspendisse sit amet bibendum lectus. Vestibulum ac massa dolor. Donec vehicula pellentesque mi, id ultrices dui cursus sit amet. Fusce sollicitudin finibus urna, eget venenatis nunc auctor id. Praesent nisl justo, venenatis ac lectus ac, blandit cursus elit. Fusce sed semper ex, eu faucibus tortor. Donec mollis imperdiet vestibulum.

Phasellus vel orci felis. Sed nec ultrices dolor. Nullam eu magna convallis, placerat lectus id, lacinia velit. Aenean feugiat ligula eu vehicula dignissim. Pellentesque dapibus velit tellus, sed ultricies nisi commodo nec. Nam eget orci lectus. Pellentesque efficitur at augue id lobortis.

Nam sit amet rhoncus magna. Phasellus facilisis erat ac ex pharetra hendrerit at non leo. Morbi non eleifend tortor. Aenean vel urna non eros imperdiet facilisis. Ut ac sapien nulla. Suspendisse turpis quam, efficitur in luctus ut, interdum vel metus. Morbi vehicula tempor lectus, eu bibendum dui consectetur vel. Curabitur efficitur rutrum ipsum eget tincidunt. Aenean fermentum ligula non lacinia mollis. Nulla sit amet neque et massa fringilla pretium sed et turpis.

Phasellus et bibendum neque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque ex elit, blandit ut pulvinar at, vestibulum ac lacus. Sed placerat bibendum ex, consequat sodales ligula tempor a. Donec nunc justo, faucibus ut nisl non, congue tristique ligula. In tempus, nisi commodo accumsan mattis, justo ex lobortis nisl, ac euismod massa risus et eros. Duis vel ultrices orci, id varius diam. Aenean ut egestas tortor.

Proin pellentesque magna et sem lacinia, id consectetur erat ultricies. In eu lacus eu ipsum placerat semper nec nec quam. Sed facilisis tincidunt dolor, id pharetra felis euismod vel. Mauris quis ante pharetra, sagittis leo non, maximus mi. Nulla in consectetur augue. Curabitur aliquam porta mi in posuere. Nam eu tempor nibh. Nunc interdum tincidunt justo, vitae pulvinar lorem vehicula non. Vestibulum nec rutrum arcu, quis sollicitudin libero. Cras lobortis euismod elit vel bibendum.

In et felis vel velit lobortis bibendum. Donec feugiat maximus tellus, vitae sodales dui pharetra sed. Cras convallis lobortis justo at semper. Vestibulum aliquam tincidunt lacus in lobortis. Ut eget euismod risus. Pellentesque a cursus lectus. Phasellus lacus ante, maximus nec sapien sed, fringilla dignissim arcu. Etiam quis leo egestas, gravida diam in, consequat est. Morbi tempus nulla eu augue vestibulum molestie. Proin sodales tempus enim ut egestas. Maecenas sed urna eget tellus tempor euismod.

Vivamus porta risus sit amet tellus sagittis mollis. Phasellus egestas purus turpis, ac aliquet erat eleifend ut. Donec posuere, arcu a varius condimentum, quam ipsum gravida nulla, non bibendum felis nisi eget justo. Nunc ut nisl eget risus scelerisque iaculis. In aliquet, quam ac feugiat imperdiet, arcu arcu molestie dolor, ut congue mi elit in elit. Donec tincidunt blandit nulla, et finibus felis sollicitudin quis. Aenean porttitor ultricies turpis, eu eleifend nulla suscipit sit amet. Curabitur hendrerit sagittis diam, quis imperdiet leo tincidunt sed. Aliquam sed risus ex. Nam facilisis leo non lorem venenatis condimentum.

Maecenas sagittis lobortis luctus. Nullam semper vitae ligula ut porttitor. Curabitur gravida at lorem non condimentum. Mauris orci nunc, euismod et nibh at, eleifend hendrerit justo. Ut fermentum egestas dignissim. Morbi ultrices mi urna, id pharetra sem placerat quis. Aliquam nec fermentum eros. Proin scelerisque sem vitae tellus pellentesque pellentesque. Morbi metus nibh, ornare ac ligula in, accumsan imperdiet magna. Donec maximus laoreet tellus, sed varius leo iaculis vitae. Sed ultrices id nunc eu luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris vehicula mauris eu sem volutpat sollicitudin.

Etiam placerat vestibulum risus. Nam in fringilla ex. Duis et vulputate risus. Sed rhoncus purus sit amet finibus condimentum. Proin in vulputate justo, id maximus elit. In lorem tellus, faucibus ut luctus id, vehicula ut quam. Donec sodales, risus rutrum euismod bibendum, massa est pellentesque lorem, ut mollis ante nunc non tellus. Morbi sit amet sem ante. In hendrerit ornare leo vitae congue. Etiam sodales risus est, quis venenatis justo mollis ac. Ut et consectetur nunc.

Mauris a velit sed felis bibendum commodo. Quisque faucibus augue quis leo pellentesque hendrerit. Praesent a purus massa. Duis sit amet tellus sit amet odio dictum porttitor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut enim a arcu volutpat scelerisque. Nunc quis ex lacus. Quisque ac massa vitae neque sollicitudin tempus. Mauris bibendum purus et pellentesque feugiat. Cras sit amet lectus a ex posuere commodo. Mauris ac luctus odio.tunheosntuhientihesuohisnteuhitheu`
}
